"""adicionado tabela de sessions

Revision ID: 0a897dc48036
Revises: 0be4e3dfb909
Create Date: 2025-09-03 16:51:58.663081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a897dc48036'
down_revision = '0be4e3dfb909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reuniao_participantes', schema=None) as batch_op:
        batch_op.drop_index('idx_participantes_reuniao')
        batch_op.drop_index('idx_participantes_usuario')
        batch_op.drop_index('participante_unico')

    op.drop_table('reuniao_participantes')
    with op.batch_alter_table('company_obligations', schema=None) as batch_op:
        batch_op.drop_index('uq_company_obligation')

    op.drop_table('company_obligations')
    with op.batch_alter_table('reunioes', schema=None) as batch_op:
        batch_op.drop_index('idx_reunioes_data')

    op.drop_table('reunioes')
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.alter_column('envio_fisico',
               existing_type=mysql.VARCHAR(length=50),
               type_=app.models.tables.JsonString(length=200),
               existing_nullable=True)
        batch_op.alter_column('observacao_importacao',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('observacao_contato',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('metodo_importacao',
               existing_type=mysql.VARCHAR(length=200),
               type_=app.models.tables.JsonString(length=255),
               existing_nullable=True)
        batch_op.drop_index('idx_empresa_tipo')
        batch_op.drop_constraint('fk_dep_emp', type_='foreignkey')
        batch_op.drop_column('envio_fisico_outro')
        batch_op.drop_column('envio_digital_fisico')

    with op.batch_alter_table('inclusoes', schema=None) as batch_op:
        batch_op.alter_column('pergunta',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('resposta',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('meeting_room_events', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('tbl_empresas', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=18),
               nullable=False)
        batch_op.alter_column('data_abertura',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('tributacao',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('regime_lancamento',
               existing_type=mysql.VARCHAR(length=500),
               type_=app.models.tables.JsonString(length=50),
               nullable=False)
        batch_op.alter_column('sistemas_consultorias',
               existing_type=mysql.VARCHAR(length=500),
               type_=app.models.tables.JsonString(length=255),
               existing_nullable=True)
        batch_op.alter_column('acessos',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=app.models.tables.JsonString(length=255),
               existing_nullable=True)
        batch_op.alter_column('observacao_acessos',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('codigo_empresa',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index('ix_tbl_empresas_acessorias_identifier')
        batch_op.create_unique_constraint(None, ['cnpj'])
        batch_op.drop_column('acessorias_identifier')
        batch_op.drop_column('created_at')
        batch_op.drop_column('acessorias_company_id')
        batch_op.drop_column('acessorias_synced_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acessorias_synced_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('acessorias_company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('acessorias_identifier', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_tbl_empresas_acessorias_identifier', ['acessorias_identifier'], unique=True)
        batch_op.alter_column('codigo_empresa',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('observacao_acessos',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('acessos',
               existing_type=app.models.tables.JsonString(length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
        batch_op.alter_column('sistemas_consultorias',
               existing_type=app.models.tables.JsonString(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('regime_lancamento',
               existing_type=app.models.tables.JsonString(length=50),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('tributacao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('data_abertura',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('meeting_room_events', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('inclusoes', schema=None) as batch_op:
        batch_op.alter_column('resposta',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('pergunta',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envio_digital_fisico', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('envio_fisico_outro', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key('fk_dep_emp', 'tbl_empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_empresa_tipo', ['empresa_id', 'tipo'], unique=False)
        batch_op.alter_column('metodo_importacao',
               existing_type=app.models.tables.JsonString(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('observacao_contato',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('observacao_importacao',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('envio_fisico',
               existing_type=app.models.tables.JsonString(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('reunioes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data_reuniao', sa.DATE(), nullable=False, comment='Data da reunião'),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False, comment='Hora de início da reunião'),
    sa.Column('hora_fim', mysql.TIME(), nullable=False, comment='Hora de fim da reunião'),
    sa.Column('assunto', mysql.VARCHAR(length=500), nullable=False, comment='Assunto da reunião'),
    sa.Column('descricao', mysql.TEXT(), nullable=True, comment='Descrição detalhada da reunião'),
    sa.Column('status', mysql.ENUM('agendada', 'em_andamento', 'concluida', 'cancelada'), server_default=sa.text("'agendada'"), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False, comment='Data e hora da criação'),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('reunioes', schema=None) as batch_op:
        batch_op.create_index('idx_reunioes_data', ['data_reuniao'], unique=False)

    op.create_table('company_obligations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('entregues', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('atrasadas', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('proximos_30d', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('futuras_30p', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['tbl_empresas.id'], name='company_obligations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('company_obligations', schema=None) as batch_op:
        batch_op.create_index('uq_company_obligation', ['company_id', 'nome'], unique=True)

    op.create_table('reuniao_participantes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('reuniao_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='ID da reunião'),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='ID do usuário participante'),
    sa.Column('username_usuario', mysql.VARCHAR(length=255), nullable=False, comment='Username do usuário no momento da criação'),
    sa.Column('status_participacao', mysql.ENUM('confirmado', 'pendente', 'recusado'), server_default=sa.text("'pendente'"), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], name='reuniao_participantes_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reuniao_id'], ['reunioes.id'], name='reuniao_participantes_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('reuniao_participantes', schema=None) as batch_op:
        batch_op.create_index('participante_unico', ['reuniao_id', 'id_usuario'], unique=True)
        batch_op.create_index('idx_participantes_usuario', ['id_usuario'], unique=False)
        batch_op.create_index('idx_participantes_reuniao', ['reuniao_id'], unique=False)

    # ### end Alembic commands ###
