"""add_birthday_recurrence_fields

Revision ID: 0d86f3268345
Revises: 0ced72e2ce85
Create Date: 2025-10-27 13:27:47.066115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d86f3268345'
down_revision = '0ced72e2ce85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday_recurs_annually', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('birthday_recurrence_years', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_calendar_events', schema=None) as batch_op:
        batch_op.drop_column('birthday_recurrence_years')
        batch_op.drop_column('birthday_recurs_annually')
    # ### end Alembic commands ###
