"""add_push_subscriptions_table

Revision ID: b57bef681887
Revises: 5a9391b4ba25
Create Date: 2025-10-22 14:52:48.426976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b57bef681887'
down_revision = '5a9391b4ba25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_setores')
    op.drop_table('management_events')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index('ix_dashboards_user_id')

    op.drop_table('dashboards')
    op.drop_table('balancetes_importados')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('workload',
               existing_type=mysql.VARCHAR(length=50),
               type_=app.models.tables.TolerantTime(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('schedule_start',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('schedule_end',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('completion_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_column('schedule')

    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.alter_column('envio_fisico',
               existing_type=mysql.VARCHAR(length=50),
               type_=app.models.tables.JsonString(length=200),
               existing_nullable=True)
        batch_op.alter_column('observacao_importacao',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('observacao_contato',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('metodo_importacao',
               existing_type=mysql.VARCHAR(length=200),
               type_=app.models.tables.JsonString(length=255),
               existing_nullable=True)
        batch_op.drop_index('idx_empresa_tipo')
        batch_op.drop_constraint('fk_dep_emp', type_='foreignkey')
        batch_op.drop_column('envio_digital_fisico')
        batch_op.drop_column('envio_fisico_outro')

    with op.batch_alter_table('diretoria_events', schema=None) as batch_op:
        batch_op.alter_column('photos',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('inclusoes', schema=None) as batch_op:
        batch_op.alter_column('pergunta',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('resposta',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('reuniao_participantes', schema=None) as batch_op:
        batch_op.alter_column('reuniao_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='ID da reunião',
               existing_nullable=False)
        batch_op.alter_column('id_usuario',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='ID do usuário participante',
               existing_nullable=False)
        batch_op.alter_column('username_usuario',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Username do usuário no momento da criação',
               existing_nullable=False)
        batch_op.alter_column('status_participacao',
               existing_type=mysql.ENUM('confirmado', 'pendente', 'recusado'),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'pendente'"))
        batch_op.alter_column('data_criacao',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index('idx_participantes_reuniao')
        batch_op.drop_index('idx_participantes_usuario')
        batch_op.drop_index('participante_unico')
        batch_op.drop_constraint('reuniao_participantes_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_usuario'], ['id'])

    with op.batch_alter_table('reunioes', schema=None) as batch_op:
        batch_op.alter_column('inicio',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
        batch_op.alter_column('fim',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
        batch_op.alter_column('assunto',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=50),
               comment=None,
               existing_comment='Assunto da reunião',
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Descrição detalhada da reunião',
               existing_nullable=True)
        batch_op.alter_column('meet_host_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('meet_settings',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=False)
        batch_op.alter_column('criador_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('data_criacao',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Data e hora da criação',
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index('idx_reunioes_criada_por')
        batch_op.drop_index('ix_reunioes_owner_id')
        batch_op.drop_constraint('fk_reunioes_criador', type_='foreignkey')
        batch_op.drop_constraint('fk_reunioes_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['meet_host_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['criador_id'], ['id'])
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('status_override')
        batch_op.drop_column('criada_por')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_assigned_to', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_parent', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_completed_by', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['completed_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])
        batch_op.create_foreign_key(None, 'tasks', ['parent_id'], ['id'])

    with op.batch_alter_table('tbl_empresas', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=18),
               nullable=False)
        batch_op.alter_column('data_abertura',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('tributacao',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('regime_lancamento',
               existing_type=mysql.VARCHAR(length=500),
               type_=app.models.tables.JsonString(length=50),
               nullable=False)
        batch_op.alter_column('sistemas_consultorias',
               existing_type=mysql.VARCHAR(length=500),
               type_=app.models.tables.JsonString(length=255),
               existing_nullable=True)
        batch_op.alter_column('acessos',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=app.models.tables.JsonString(length=255),
               existing_nullable=True)
        batch_op.alter_column('observacao_acessos',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('codigo_empresa',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('ativo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_index('ix_tbl_empresas_acessorias_identifier')
        batch_op.create_unique_constraint(None, ['cnpj'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('acessorias_synced_at')
        batch_op.drop_column('acessorias_identifier')
        batch_op.drop_column('acessorias_company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acessorias_company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acessorias_identifier', mysql.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('acessorias_synced_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_tbl_empresas_acessorias_identifier', ['acessorias_identifier'], unique=True)
        batch_op.alter_column('ativo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('codigo_empresa',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('observacao_acessos',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('acessos',
               existing_type=app.models.tables.JsonString(length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
        batch_op.alter_column('sistemas_consultorias',
               existing_type=app.models.tables.JsonString(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('regime_lancamento',
               existing_type=app.models.tables.JsonString(length=50),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('tributacao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('data_abertura',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_completed_by', 'users', ['completed_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_tasks_parent', 'tasks', ['parent_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_tasks_assigned_to', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('reunioes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('criada_por', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('status_override', mysql.ENUM('AGENDADA', 'EM_ANDAMENTO', 'REALIZADA', 'ADIADA', 'CANCELADA'), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_reunioes_owner_id_users', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_reunioes_criador', 'users', ['criador_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_reunioes_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('idx_reunioes_criada_por', ['criada_por'], unique=False)
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               comment='Data e hora da criação',
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('criador_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('meet_settings',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=True)
        batch_op.alter_column('meet_host_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('descricao',
               existing_type=mysql.TEXT(),
               comment='Descrição detalhada da reunião',
               existing_nullable=True)
        batch_op.alter_column('assunto',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=500),
               comment='Assunto da reunião',
               existing_nullable=False)
        batch_op.alter_column('fim',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
        batch_op.alter_column('inicio',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)

    with op.batch_alter_table('reuniao_participantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reuniao_participantes_ibfk_2', 'users', ['id_usuario'], ['id'], ondelete='CASCADE')
        batch_op.create_index('participante_unico', ['reuniao_id', 'id_usuario'], unique=True)
        batch_op.create_index('idx_participantes_usuario', ['id_usuario'], unique=False)
        batch_op.create_index('idx_participantes_reuniao', ['reuniao_id'], unique=False)
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status_participacao',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('confirmado', 'pendente', 'recusado'),
               nullable=True,
               existing_server_default=sa.text("'pendente'"))
        batch_op.alter_column('username_usuario',
               existing_type=mysql.VARCHAR(length=255),
               comment='Username do usuário no momento da criação',
               existing_nullable=False)
        batch_op.alter_column('id_usuario',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ID do usuário participante',
               existing_nullable=False)
        batch_op.alter_column('reuniao_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ID da reunião',
               existing_nullable=False)

    with op.batch_alter_table('inclusoes', schema=None) as batch_op:
        batch_op.alter_column('resposta',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('pergunta',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('diretoria_events', schema=None) as batch_op:
        batch_op.alter_column('photos',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envio_fisico_outro', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('envio_digital_fisico', mysql.VARCHAR(length=200), nullable=True))
        batch_op.create_foreign_key('fk_dep_emp', 'tbl_empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_empresa_tipo', ['empresa_id', 'tipo'], unique=False)
        batch_op.alter_column('metodo_importacao',
               existing_type=app.models.tables.JsonString(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('observacao_contato',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('observacao_importacao',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('envio_fisico',
               existing_type=app.models.tables.JsonString(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('completion_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('schedule_end',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('schedule_start',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('workload',
               existing_type=app.models.tables.TolerantTime(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)

    op.create_table('balancetes_importados',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('periodo_1_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('periodo_2_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('arquivo_1', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('arquivo_2', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tabela_comparativa', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dashboards',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('balancete_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('chart_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('configuracao', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['balancete_id'], ['balancetes_importados.id'], name='dashboards_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index('ix_dashboards_user_id', ['user_id'], unique=False)

    op.create_table('management_events',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('event_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('event_date', sa.DATE(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('attendees_internal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('attendees_external', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('participants_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('include_breakfast', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('cost_breakfast', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('include_lunch', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('cost_lunch', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('include_snack', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('cost_snack', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('other_materials', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('event_total', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('attendance_scope', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('breakfast_items', mysql.TEXT(), nullable=True),
    sa.Column('lunch_items', mysql.TEXT(), nullable=True),
    sa.Column('dinner_items', mysql.TEXT(), nullable=True),
    sa.Column('include_dinner', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('cost_dinner', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='management_events_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_setores',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('setor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], name='user_setores_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_setores_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'setor_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
