"""Migração limpa inicial

Revision ID: e5d8e8454900
Revises: 
Create Date: 2025-08-28 14:55:46.535432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5d8e8454900'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acessorias_company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acessorias_identifier', mysql.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('acessorias_synced_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_tbl_empresas_acessorias_identifier', ['acessorias_identifier'], unique=True)
        batch_op.alter_column('codigo_empresa',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('observacao_acessos',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('acessos',
               existing_type=app.models.tables.JsonString(length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
        batch_op.alter_column('sistemas_consultorias',
               existing_type=app.models.tables.JsonString(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('regime_lancamento',
               existing_type=app.models.tables.JsonString(length=50),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('tributacao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('data_abertura',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envio_fisico_outro', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('envio_digital_fisico', mysql.VARCHAR(length=200), nullable=True))
        batch_op.create_foreign_key('fk_dep_emp', 'tbl_empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_empresa_tipo', ['empresa_id', 'tipo'], unique=False)
        batch_op.alter_column('metodo_importacao',
               existing_type=app.models.tables.JsonString(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('observacao_contato',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('observacao_importacao',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('envio_fisico',
               existing_type=app.models.tables.JsonString(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('company_obligations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('entregues', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('atrasadas', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('proximos_30d', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('futuras_30p', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['tbl_empresas.id'], name='company_obligations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('company_obligations', schema=None) as batch_op:
        batch_op.create_index('uq_company_obligation', ['company_id', 'nome'], unique=True)

    # ### end Alembic commands ###
